services:
  backend:
    image: ispire.web
    build:
      context: .
      dockerfile: ISpire.Web/Dockerfile
    ports:
      - 5000:8080

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
