services:
  backend:
    build:
      context: .
      dockerfile: ISpire.Web/Dockerfile.dev
    image: ispire.web:dev
    ports:
      - "7000:6000"
    env_file:
        - .env
    depends_on:
      - db
    volumes:
      - ./:/workspace
      - /workspace/ISpire.Web/bin
      - /workspace/ISpire.Web/obj
      - /workspace/ISpire.Core/bin
      - /workspace/ISpire.Core/obj
      - /workspace/ISpire.Infrastructure/bin
      - /workspace/ISpire.Infrastructure/obj

  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
