services:
  backend:
    image: ispire.web:dev
    build:
      context: .
      dockerfile: ISpire.Web/Dockerfile.dev
    ports:
      - "8041:8041"
    env_file:
        - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/workspace
      - /workspace/ISpire.Web/bin
      - /workspace/ISpire.Web/obj
      - /workspace/ISpire.Core/bin
      - /workspace/ISpire.Core/obj
      - /workspace/ISpire.Infrastructure/bin
      - /workspace/ISpire.Infrastructure/obj

  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
