services:
  backend:
    image: ghcr.io/xirzo/ispire-backend:latest
    ports:
      - 8041:8041
    secrets:
      - ispire_db_connection_string
    environment:
      DB_CONNECTION_STRING: /run/secrets/ispire_db_connection_string
      JWT_KEY: /run/secrets/jwt_key
      JWT_ISSUER: /run/secrets/jwt_issuer
      JWT_AUDIENCE: /run/secrets/jwt_audience

secrets:
  ispire_db_connection_string:
    external: true
  jwt_key:
    external: true
  jwt_issuer:
    external: true
  jwt_audience:
    external: true
