services:
  backend:
    image: ghcr.io/xirzo/ispire-backend:latest
    secrets:
      - ispire_db_connection_string
    environment:
      DB_CONNECTION_STRING: /run/secrets/ispire_db_connection_string
      JWT_KEY: /run/secrets/jwt_key
      JWT_ISSUER: /run/secrets/jwt_issuer
      JWT_AUDIENCE: /run/secrets/jwt_audience
    networks:
        - traefik_proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ispire.rule=Host(`test.api.ispire.ru`)"
        - "traefik.http.services.ispire.loadbalancer.server.port=8041"
        - "traefik.http.routers.ispire.entrypoints=web,https"
        - "traefik.http.routers.ispire.tls.certresolver=letsencrypt"

        - "traefik.http.routers.ispire-http.rule=Host(`test.api.ispire.ru`)"
        - "traefik.http.routers.ispire-http.entrypoints=web"
        - "traefik.http.routers.ispire-http.middlewares=redirect-to-https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
networks:
  traefik_proxy:
    external: true

secrets:
  ispire_db_connection_string:
    external: true
  jwt_key:
    external: true
  jwt_issuer:
    external: true
  jwt_audience:
    external: true
