services:
  backend:
    build:
      context: .
      dockerfile: ISpire.Web/Dockerfile.dev
    image: ispire.web:dev
    ports:
      - "6000:6000"
    secrets:
      - db_connection_string
    environment:
      ASPNETCORE_HTTP_PORTS: 6000
      DB_CONNECTION_STRING: /run/secrets/db_connection_string
    depends_on:
      - db
    volumes:
      - ./:/workspace
      - /workspace/ISpire.Web/bin
      - /workspace/ISpire.Web/obj
      - /workspace/ISpire.Core/bin
      - /workspace/ISpire.Core/obj
      - /workspace/ISpire.Infrastructure/bin
      - /workspace/ISpire.Infrastructure/obj

  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    secrets:
      - db_password
      - db_user
      - db_name
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_DB_FILE: /run/secrets/db_name

secrets:
  db_connection_string:
    file: db_connection_string.txt
  db_password:
    file: db_password.txt
  db_user:
    file: db_user.txt
  db_name:
    file: db_name.txt
