FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app
COPY ISpire.sln ./
COPY ISpire.Web/ISpire.Web.csproj ISpire.Web/
COPY ISpire.Core/ISpire.Core.csproj ISpire.Core/
COPY ISpire.IO/ISpire.IO.csproj ISpire.IO/
RUN dotnet restore ISpire.Web/ISpire.Web.csproj
CMD ["dotnet", "watch", "--project", "ISpire.Web/ISpire.Web.csproj", "run", "--urls=http://0.0.0.0:8080"]
