name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p "${{ secrets.HOST_SSH_PORT }}" -H "${{ secrets.HOST_DOMAIN }}" >> ~/.ssh/known_hosts

      - name: Create context
        run: |
          docker context inspect vps || \
          docker context create vps --docker "host=ssh://${{ secrets.HOST_USERNAME}}@${{ secrets.HOST_SSH_DOMAIN }}:${{ secrets.HOST_SSH_PORT }}"

      - name: Build the backend image
        run: docker build -f ISpire.Web/Dockerfile -t ghcr.io/xirzo/ispire-backend:latest .

      - name: Push the backend image
        run: docker push ghcr.io/xirzo/ispire-backend:latest

      - name: Use VPS context
        run: docker context use vps

      - name: Deploy to VPS
        run: docker stack deploy ispire-backend -c docker-swarm.yaml --with-registry-auth
